name: RoboSatsExp
options:
  bundleIdPrefix: com.robosats
  deploymentTarget:
    iOS: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
targets:
  RoboSatsExp:
    type: application
    platform: iOS
    sources:
      - path: RoboSatsExp
        excludes:
          - Resources/WebApp
          - Resources/Raw
    resources:
      - path: RoboSatsExp/Resources/WebApp
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.robosats.exp.ios
        PRODUCT_NAME: RoboSatsExp
        MARKETING_VERSION: 0.1.0
        CURRENT_PROJECT_VERSION: 1001001
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Config/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_OBJC_BRIDGING_HEADER: RoboSatsExp/Support/RoboSatsExp-Bridging-Header.h
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/tor-native/target/aarch64-apple-ios/release
        OTHER_LDFLAGS:
          - $(inherited)
          - -larti_mobile
          - -framework
          - Security
          - -framework
          - SystemConfiguration
          - -lz
          - -lresolv
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets: []
