import { afterEach, describe, expect, it, vi } from "vitest";
import { generatePgpKeyPairOffMainThread } from "@/domains/crypto/pgpKeyGenerationClient";

const generationMocks = vi.hoisted(() => ({
  generatePgpKeyPairOnCurrentThread: vi.fn()
}));

vi.mock("@/domains/crypto/pgpKeyGeneration", () => generationMocks);

const workerKeys = {
  publicKeyArmored: "worker-public-key",
  encryptedPrivateKeyArmored: "worker-private-key"
};
const fallbackKeys = {
  publicKeyArmored: "fallback-public-key",
  encryptedPrivateKeyArmored: "fallback-private-key"
};

describe("PGP key generation client", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
    generationMocks.generatePgpKeyPairOnCurrentThread.mockReset();
  });

  it("returns key material generated by a worker", async () => {
    const worker = installWorkerStub((instance) => {
      instance.onmessage?.({ data: { ok: true, keyPair: workerKeys } } as MessageEvent);
    });

    await expect(generatePgpKeyPairOffMainThread("private-test-token")).resolves.toEqual(workerKeys);
    expect(worker.instances).toHaveLength(1);
    expect(worker.instances[0]?.messages).toEqual([{ highEntropyToken: "private-test-token" }]);
    expect(worker.instances[0]?.terminated).toBe(true);
    expect(generationMocks.generatePgpKeyPairOnCurrentThread).not.toHaveBeenCalled();
  });

  it("coalesces concurrent generation for the same robot token", async () => {
    let complete: ((worker: WorkerStub) => void) | undefined;
    const worker = installWorkerStub(() => {
      complete = (pendingWorker) => {
        pendingWorker.onmessage?.({ data: { ok: true, keyPair: workerKeys } } as MessageEvent);
      };
    });

    const first = generatePgpKeyPairOffMainThread("shared-private-test-token");
    const second = generatePgpKeyPairOffMainThread("shared-private-test-token");
    expect(worker.instances).toHaveLength(1);
    complete?.(worker.instances[0]!);

    await expect(Promise.all([first, second])).resolves.toEqual([workerKeys, workerKeys]);
    expect(worker.instances[0]?.messages).toHaveLength(1);
  });

  it("falls back when workers cannot run", async () => {
    generationMocks.generatePgpKeyPairOnCurrentThread.mockResolvedValue(fallbackKeys);
    const worker = installWorkerStub((instance) => instance.onerror?.(new Event("error")));

    await expect(generatePgpKeyPairOffMainThread("private-test-token")).resolves.toEqual(fallbackKeys);
    expect(worker.instances[0]?.terminated).toBe(true);
    expect(generationMocks.generatePgpKeyPairOnCurrentThread).toHaveBeenCalledWith("private-test-token");
  });

  it("falls back when posting work fails", async () => {
    generationMocks.generatePgpKeyPairOnCurrentThread.mockResolvedValue(fallbackKeys);
    const worker = installWorkerStub(() => {
      throw new Error("worker protocol unavailable");
    });

    await expect(generatePgpKeyPairOffMainThread("private-test-token")).resolves.toEqual(fallbackKeys);
    expect(worker.instances[0]?.terminated).toBe(true);
    expect(generationMocks.generatePgpKeyPairOnCurrentThread).toHaveBeenCalledOnce();
  });

  it("falls back when a worker returns malformed key material", async () => {
    generationMocks.generatePgpKeyPairOnCurrentThread.mockResolvedValue(fallbackKeys);
    const worker = installWorkerStub((instance) => {
      instance.onmessage?.({ data: { ok: true, keyPair: null } } as MessageEvent);
    });

    await expect(generatePgpKeyPairOffMainThread("private-test-token")).resolves.toEqual(fallbackKeys);
    expect(worker.instances[0]?.terminated).toBe(true);
    expect(generationMocks.generatePgpKeyPairOnCurrentThread).toHaveBeenCalledOnce();
  });

  it("terminates a stalled worker and falls back after the deadline", async () => {
    vi.useFakeTimers();
    generationMocks.generatePgpKeyPairOnCurrentThread.mockResolvedValue(fallbackKeys);
    const worker = installWorkerStub(() => undefined);

    const generation = generatePgpKeyPairOffMainThread("private-test-token");
    await vi.advanceTimersByTimeAsync(60_000);

    await expect(generation).resolves.toEqual(fallbackKeys);
    expect(worker.instances[0]?.terminated).toBe(true);
    expect(generationMocks.generatePgpKeyPairOnCurrentThread).toHaveBeenCalledOnce();
  });
});

interface WorkerStub {
  messages: unknown[];
  onerror: ((event: Event) => void) | null;
  onmessage: ((event: MessageEvent) => void) | null;
  terminated: boolean;
}

function installWorkerStub(onPostMessage: (worker: WorkerStub) => void) {
  const instances: WorkerStub[] = [];
  class TestWorker implements WorkerStub {
    messages: unknown[] = [];
    onerror: ((event: Event) => void) | null = null;
    onmessage: ((event: MessageEvent) => void) | null = null;
    terminated = false;

    constructor() {
      instances.push(this);
    }

    postMessage(message: unknown) {
      this.messages.push(message);
      onPostMessage(this);
    }

    terminate() {
      this.terminated = true;
    }
  }
  vi.stubGlobal("Worker", TestWorker);
  return { instances };
}
